spring:
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
    hibernate:
      ddl-auto: update
#  database:
#    driverClassName: "com.mysql.jdbc.driver"

  datasource:
      url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
      username: "root"
      password: "root"
      test-while-idle: "true"
      validationQuery: "SELECT 1"
      driver-class-name: "com.mysql.jdbc.Driver"
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration"
server:
  port: 8082