spring:
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
    hibernate:
      ddl-auto: update
#  database:
#    driverClassName: "com.mysql.jdbc.driver"

  datasource:
      url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
      username: "root"
      password: "{cipher}23035c630026ce46f3600f9c32b800418bd95ef093ee3d6542516f0e0d83e64a"
      test-while-idle: "true"
      validationQuery: "SELECT 1"
      driver-class-name: "com.mysql.jdbc.Driver"
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration"
server:
  port: 8081
  
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://localhost:8761/eureka/
